### ISSUE TITLE
Where to add Authorization Files?

### ISSUE THREAD

**Issue by marijani101** [gocondor/gocondor#46]
Hey there, your doing great work.
I was trying to add casbin policies to work with the db, but i am having some issues since i have to initialize the gorm adapter `gormadapter.NewAdapterByDB`.  Any help will be appreciated.
Thanks in advance.

**Comment by hsluoyz** [comment]
@marijani101 can you show some details like what error you have seen?

**Comment by harranali** [comment]
Hi @marijani101 ,
`gormadapter.NewAdapterByDB` accepts an instance of GORM
you can resolve the instance of GORM by calling the method `Resolve` in the database package,
first import it `import "github.com/gocondor/core/database"`
then resolve the instance `database.Resolve()`

**Comment by marijani101** [comment]
> i101 ,
> `gormadapter.NewAdapterByDB` accepts an instance of GORM
> you can resolve the instance of GORM by calling the method `Resolve` in the database package,
> first import it `import "github.com/gocondor/core/database"`
> then resolve the instance `database.Resolve()`

Thanks alot!! 
I used the `database.Resolve()` func and it worked out great! thanks!!
