### ISSUE TITLE
Adding Router Groups

### ISSUE THREAD

**Issue by marijani101** [gocondor/gocondor#47]
Is it possible to create router groups?

ie: `v1 := r.Group (v1)`

Then use it as normal for other routes

ie:  `v1.Get("/users/all", handlers.UsersGetAll)`

Thanks in advance

**Comment by harranali** [comment]
Hi @marijani101 
I just released the support of routing groups
please have a look
https://gocondor.github.io/docs/routing/

**Comment by marijani101** [comment]
I just read it, thanks a lot!!
Keep up the great work!
