### ISSUE TITLE
Sqlite db not found

### ISSUE THREAD

**Issue by marijani101** [gocondor/gocondor#49]
Hello, 

it seems that there is an issue with the env key used to select the sqlite db to be used. 

it is written as. `SQLITE_DB`  instead of  `SQLITE_FILE`

Also, while there, os.stats references `../../dbName` instead of. `dbName`

using `gocondor version v1.1.0`

**Comment by harranali** [comment]
Hi @marijani101,
I will have a look at it.
Thank you.

**Comment by harranali** [comment]
fixed now @marijani101 
Thanks.
